language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
branches:
  only:
    - development
script:
  - npm run lint
deploy:
  provider: heroku
  on:
    repo: cade-onibus/cade-onibus-backend
    branch: development
  api_key:
    secure: tWTFDZ90TxqnFzd9fKmZuMfjo1JBef8Mxt5+MGn6UmThgd6PTE3UQK7+08+WlkYh/XH+30672qA69ZO3VCs+7sAG9ZIPJ4ZXj4gW/kDnAe0PTxMigu1DCSuF9d0DgYyBZwgchbWC7bOF47V4u6AXbZsx8GZpBuEf203naLjqHR3YqyNiQKuf54mDWmP4rB4/OyTBNol69cwmrqvLrJJL94A0qw3US3qf7Kv/8v0MO+dRtbBBGZUccJx7yyakojlAu2pIDMTYjYB9NeCY3KQF2yGNTBJ9MK4pNBS48miIn7hHnUhp+f6UFjzLySgNBQo97fQhUjW1jpq8g2m3olF+Z/kXEZX71MR1TgtdThiXg6xgKc/SZjdobn9Z7ThdFCMI76G/VstKZcw9yQn7eiuTWIAatTs5XrLVNU/CCVfuovXnjaSktJWdhwdpC6Eb1iMwqF5PFyFmcYSTbYIgPUdUo7+4G0Z0VKdWieJ4dNwg/dqUe5j8degkIgNst/A/wclpefVtlR3zFdRbzu1rGcMPfHL6yqU/sYnOeU7+kNKzsMgICALrr5AIwM0ArQungD+t6jboGTriSH2s+XbheeC0NTTxAwcoF+lkUUFca1GuSYBiDnSCkzX1zo6yerRm62eKQ71T1zd/+/VTSE6aziZUbfmHxZAL7U0aBypVfjS6T5E=
  app: cade-onibus-development
env:
  global:
    - secure: B5S3eT1txjPpCecWcmSj7S8Lnv06Bp9TpMGhwAHaup3qlqwl3z6+lr6krKkgJ0CnAmSMqNRxK7/bFKfmAQYd73pIkZYUS2c/G5op3vDGBZOCSB2AN1ThK0HtdZWDwqa2agQ9naqJcNDql8+xF5wsUGaoZgoBG6JRTdEvb5MKNqtKCfpL4ZvpiPmCATquJaDPVcWl9yJfwuxnaEvUGeaYMFNUbWViPD36VNZeEbjAt9jSG8YCjSp61SYi33ErFJgEdNHBg+6K4XOh84auynuJVeAL+2VhuK3J8CCJ6RF5HBR/JdHZkPWgiwYBp9hNh55u01p/ZrbjPGHB+yATbkHPpzBLNbsaQLtXfaDnhtCCweN6GMAo/ZlyWyORBiRGO91Fe9StfYr/GMVPGn3EUCfJAIzFLoLHcLZ2aqzMFY8AAE/DtW62MHvapOjnDAujnv7ExQ0TfQcgnXEDFuYgopsX6yZAiPhSKR0AYaO8rlADlAFckIawEx2IdRgXIkDRE8a2wdz140jjvBNjNfbNLnOSgt2KRmTmgZAT1MUxQok4DdHOUHEBAb2EZnFeIC2UwUdD0Oisec5BSOlgpcqjHMHpOtmtX6KNn/Jf+vMMrsT2xEp+w2PDLYnsv3HQU9wd5Jfv+HnZoE7WOQ56urRfICU1sTYiFeHJBTZatMGBqdboxMc=
    - secure: DERReKrenFzCPTJFuoxcSUxn1ABfWzydEIttx+bLcABxxn3ioPEXnDRhs/mguQul1BRL6j29N4tQruQl+QtlvwmxPCwMeGTLpl+/18woEcQzUL03yRBsRpnZ4omfuHDfGhhCTX0KgLTwxkJ3P4JVCLpQLgwzuflv6hHjKDRB8xZllb062RI0Zlfk7Ctp0eD5K+9aPnOKH4WmgtIomK/7baCSpr/gfs4RWNFDK1QVZs9Egbz+oM+K3k0PV2U/8ABRZw0Ro+09eXAdx0bzY0xvc02n17t0OXJ2uZcHjfDBU4TFLW9Ok7T9c338ZU7H2kj7jhc4Rs5xGarxbP6NH1fnG3CLyi4+HTjmN7AFSkmWPYf1oA1O+HQHzp5Ztmd5Y9RD4n+Z6uHmjMi2RcnrzEeL++oQp8vciS0gu9XcoOu7JlmBTA9OobZpw+WhX6yqaLLK6FGOVYbqGiVi1RbntQZ20w9uwwrMQq0YEg5DsboE4ieH4v9wxDhsQxEb7JvQCjz5G2k05/y79bEpun3mxm85HfEIZbkGWZF7atkQ+pce/yzdsX7Ws9Hg4mxybtxZxaXL3Qjpyy/GtSmDkY4j3gmSzvUyZMxcb5e08nC14XZ+fAf1QFaAZpIN6Hg0kFpT9DTrIwJoAQUJ2MnYJKLhL2TJJxWhN0tfDb5x1kgbVorJIeI=
    - secure: tnsmSaPepE4tIWeBOq9DkHUBjyMdzf9+UAk3KCmIELLO079FrH8KeEIyKlCiJwfSyxLqdWkpCZHuDUbR9TkBFJF18ahkEAI3oNzov2qs5VWmhndwK6pItK4AU3MDCGLyOP7IRz+UaVMxi9PhwLalHhhziHrhSVr4BLAxODvRHJcCReqQ6VXsWNA8Rxx0nNzP/QwfKdedbA45iXG9nbOZEsPR4VlQ+HrxlUkfPESkdX9BSiEN6FlQirZTTHwN3scfxSFdnGdrPb4fh59yldQfEV2ARNOaD4JeD7RpjyslDjKaGt/ru4VYVFKp9n1bCbW8+eqFWEi6QW3bEimAx8SpSo7sfNRXI937BhE5ZdgKFYthhSaQjpLiHrzhmTkptLke8HtG1PXHYWCWgYzAZuLaCrWItn4Z+D5TAnsZxia2t/ltlTiGylla9ZGkvTBLxda+iNFysic85zyLLiguDndjcW42li+CnvX7quykWjor6CFjd+zzdneMDgxObcwq8yBrcO3CcySFm6mDsN/aH7pUDH0OcWzt6tLEJDTCSuO/YVzHADqTXaq8bxZL8YLZtkTYUpb2m2jCvrowP7rVZVs6GGLtAQgZ2q5Rdu7eBhcogZSzXctJabAKMe4GXd24Q6Wpyo6tP+V9erhKtE3Ebt7NNbhLwbIwFMFudEFk6YeqP4k=
notifications:
  email: false
