language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
# blockList
branches:
  except:
    - master
    - production
#deploy:
#  provider: heroku
#  api_key:
#  app: cade-onibus-development
