version: '2.2'
services:
  mongoDB:
    image: mongo
    container_name: mongoDB
    ports:
      - 27017:27017
  elasticsearch:
    image: elasticsearch:6.7.0
    container_name: elasticsearch
    ports:
      - 9200:9200
