version: '2.2'
services:
  mongoDB:
    image: mongo
    container_name: mongoDB
    ports:
      - 27017:27017
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: elasticsearch
    environment:
      - cluster.name=cade-onibus-cluster
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
